### ISSUE TITLE
uid.csv issue

### ISSUE THREAD

**Issue by vk4tux** [rthoelen/NXDNtools#1]
Using http://nxmanager.weebly.com/uploads/7/1/2/0/71209569/nxuid_export.csv > uid.csv

getting on nxcm_icom_log.py execution  ;

Traceback (most recent call last):
  File "nxcm_icom_log.py", line 48, in <module>
    if len(row[3]) > 0:
IndexError: list index out of range

**Comment by rthoelen** [comment]
Thanks, I’ll look into this.

**Comment by vk4tux** [comment]
I just cleared the file >uid.csv for now, does not seem necessary for
the server or dashboard function ;

http://nxdn.duckdns.org


-----Original Message-----

**Comment by rthoelen** [comment]
It won't mess the server up, but you may not have all data on the dashboard.  I'm going to hold off on making changes on this until I find out what the new database will look like.  For now, I cleaned the CSV so it will load (had a couple bad entries):

https://ln.sync.com/dl/6231c5dc0/v8gy7962-exmzamn8-3u8fmqcg-7sribaw7

**Comment by vk4tux** [comment]
Bob, where is the uid.csv you edited for download please?

-----Original Message-----

**Comment by rthoelen** [comment]
At this link:

https://ln.sync.com/dl/6231c5dc0/v8gy7962-exmzamn8-3u8fmqcg-7sribaw7

**Comment by vk4tux** [comment]
Thankyou, all good ;

root@ubuntu:/home/NXCore_Icom# NXCORE Manager, ICOM, version 1.3.2a
Copyright (C) Robert Thoelen, 2015-2016

Repeater Count:  4

Map data turned off



Repeater vk4tux address: 106.70.88.229

Talkgroups 3
Repeater vk4tux  Talkgroups:  100 505 65000
Tactical Talkgroups 1
Repeater 0  Tactical Talkgroup List:  0



Repeater vk2gp address: 115.187.238.159

Talkgroups 3
Repeater vk2gp  Talkgroups:  100 505 65001
Tactical Talkgroups 1
Repeater 1  Tactical Talkgroup List:  0



Repeater n5wig address: 99.17.62.232

Talkgroups 3
Repeater n5wig  Talkgroups:  100 505 65001
Tactical Talkgroups 1
Repeater 2  Tactical Talkgroup List:  0



Repeater vk2gg address: 210.185.104.158

Talkgroups 3
Repeater vk2gg  Talkgroups:  100 505 65001
Tactical Talkgroups 1
Repeater 3  Tactical Talkgroup List:  0

Repeater  ->vk4tux<-  receiving start from UID: 54035 from TG: 505 on
RAN: 1
Repeater  ->vk4tux<-  receiving stop from UID: 54035 from TG: 505



-----Original Message-----
